routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Public\OrderController;
use App\Http\Controllers\Admin\TagController;
use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\Admin\SizeController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\BrandController;
use App\Http\Controllers\Admin\ColorController;
use App\Http\Controllers\Public\CartController;
use App\Http\Controllers\Admin\CourseController;
use App\Http\Controllers\Admin\SliderController;
use App\Http\Controllers\Admin\CommentController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Public\PublicController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\DistrictController;
use App\Http\Controllers\Admin\DashboardController;

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';

Route::get('/', [PublicController::class, 'index'])->name('public.index');
Route::get('/shop', [PublicController::class, 'shop'])->name('public.shop');
// Route::get('/product', [PublicController::class, 'product'])->name('public.product');
Route::get('/category/{category}/products', [PublicController::class, 'categoryWiseProducts'])->name('public.categories.products');
Route::get('/products/{product}', [PublicController::class, 'productDetails'])->name('public.product_details');
Route::get('/cart', [PublicController::class, 'cart'])->name('public.cart');
//Route::get('/checkout', [PublicController::class, 'checkout'])->name('public.checkout');
//Route::get('/order', [PublicController::class, 'order'])->name('public.order');
Route::get('/about-us', [PublicController::class, 'aboutUs'])->name('public.about_us');

//cart routes
Route::get('/cart-items', [CartController::class, 'index'])->middleware('auth')->name('carts.index');
Route::post('products/{product}/cart', [CartController::class, 'store'])->middleware('auth')->name('public.carts.store');
Route::delete('cart-items/{cartItem}', [CartController::class, 'destroy'])->middleware('auth')->name('carts.destory');

//order routes
Route::get('/order-complete', [OrderController::class, 'index'])->name('orders.index');
Route::get('/checkout', [OrderController::class, 'create'])->middleware('auth')->name('orders.create');
Route::post('/orders', [OrderController::class, 'store'])->middleware('auth')->name('orders.store');


// ========Comment Route ==========
Route::post('/products/{product}/comments', [CommentController::class, 'store'])->name('products.comments.store')->middleware('auth');

//Route::get('/login', [AuthController::class, 'login'])->name('customer.login');

Route::prefix('admin')->name('admin.')->group(function () {

    Route::get('/', function () {
        return view('welcome');
    });

    Route::get('/dashboard', [DashboardController::class, 'index'])->middleware(['auth'])->name('dashboard.index');

    Route::get('/products', [ProductController::class, 'index'])->name('products.index');
    Route::get('/products/create', [ProductController::class, 'create'])->name('products.create');
    Route::post('/products', [ProductController::class, 'store'])->name('products.store');
    Route::get('/products/{product}', [ProductController::class, 'show'])->name('products.show');
    Route::get('/products/{product}/edit', [ProductController::class, 'edit'])->name('products.edit');
    Route::patch('/products/{product}', [ProductController::class, 'update'])->name('products.update');
    Route::delete('/products/{product}', [ProductController::class, 'destroy'])->name('products.destroy');


    Route::get('/categories/trash', [CategoryController::class, 'trash'])->name('categories.trash');
    Route::patch('/categories/trash/{id}', [CategoryController::class, 'restore'])->name('categories.restore');
    Route::delete('/categories/trash/{id}', [CategoryController::class, 'delete'])->name('categories.delete');
    Route::resource('categories', CategoryController::class);

    Route::get('/courses/trash', [CourseController::class, 'trash'])->name('courses.trash');
    Route::patch('/courses/trash/{id}', [CourseController::class, 'restore'])->name('courses.restore');
    Route::delete('/courses/trash/{id}', [CourseController::class, 'delete'])->name('courses.delete');
    Route::resource('courses', CourseController::class);
    Route::resource('/courses', CourseController::class);


    Route::resource('sizes', SizeController::class);
    Route::resource('tags', TagController::class);
    Route::resource('districts', DistrictController::class);
    Route::resource('brands', BrandController::class);
    Route::resource('colors', ColorController::class);
    ROute::resource('users', UserController::class);

    // ===============Slider==============

    Route::get('/sliders/trash', [SliderController::class, 'trash'])->name('sliders.trash');
    Route::patch('/sliders/trash/{id}', [SliderController::class, 'restore'])->name('sliders.restore');
    Route::delete('/sliders/trash/{id}', [SliderController::class, 'delete'])->name('sliders.delete');

    Route::resource('sliders', SliderController::class);
});

resources/views/admin/sizes/create.blade.php
<x-backend.layout.master>

    <x-slot:title>
        Size
        </x-slot>

        <x-slot:pageTitle>
            SIZE
            </x-slot>

            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                ADD NEW SIZE
                            </h2>
                        </div>
                        <div class="body">
                            <form class="form-horizontal" action="{{ route('admin.sizes.store') }}" method="POST">
                                @csrf

                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                        
                                        <x-forms.label for="title" text="title" />

                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line {{ $errors->has('title') ? 'focused error' : '' }}">
                                               
                                                <x-forms.input type="text" name="title" value="{{ old('title') }}" class=" @error('title') is-invalid @enderror" />

                                            </div>

                                            <x-alerts.error name="title" message="message" />

                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">
                                       
                                        <x-utilities.link-list href="{{ route('admin.sizes.index') }}" color="danger" text="back" />
                                       
                                        <x-forms.button class="m-t-15" color="primary" text="submit" />

                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

</x-backend.layout.master>

resources/views/admin/sizes/edit.blade.php
<x-backend.layout.master>

    <x-slot:title>
        Size
        </x-slot>

        <x-slot:pageTitle>
            SIZE
            </x-slot>

            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                EDIT SIZE
                            </h2>
                        </div>
                        <div class="body">
                            <form class="form-horizontal" action="{{ route('admin.sizes.update',  $size->id) }}" method="POST">
                                @csrf
                                @method('PATCH')

                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">

                                        <x-forms.label for="title" text="title" />

                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line {{ $errors->has('title') ? 'focused error' : '' }}">

                                               <x-forms.input type="text" name="title" value="{{ old('title', $size->title) }}" class=" @error('title') is-invalid @enderror" />

                                            </div>
                                            
                                            <x-alerts.error name="title" message="message" />

                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">
                                        <x-utilities.link-list href="{{ route('admin.sizes.index') }}" color="danger" text="back" />
                                        <x-forms.button class="m-t-15" color="primary" text="update" />
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

</x-backend.layout.master>

resources/views/admin/sizes/index.blade.php
<x-backend.layout.master>

    <x-slot:title>
        Size
        </x-slot>

        <x-slot:pageTitle>
            SIZE
            </x-slot>

            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                ALL SIZES
                               
                                <x-utilities.link-create href="{{ route('admin.sizes.create') }}" class="pull-right" btnType="success" text="Add New Size" icon="add"/>

                            </h2><br>
                            
                            <x-alerts.message id="sizeId" class="text-white" type="success" :message="session('message')"/>
                        </div>
                        <div class="body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                    <thead>
                                        <tr>
                                            <th>Sl</th>
                                            <th>Title</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>Sl</th>
                                            <th>Title</th>
                                            <th>Action</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        @foreach ($sizes as $size)
                                        <tr>
                                            <td>{{ $loop->iteration }}</td>
                                            <td>{{ $size->title }}</td>
                                            <td class="text-center" style="white-space:nowrap;">                                                
                                                <x-utilities.link-show href="{{ route('admin.sizes.show', $size->id) }}" text="SHOW"/>                                                
                                                <x-utilities.link-edit href="{{ route('admin.sizes.edit', $size->id) }}" text="EDIT"/>
                                                <form action="{{ route('admin.sizes.destroy', $size->id) }}" method="POST" style="display:inline">
                                                    @csrf
                                                    @method('DELETE')
                                                    <x-forms.button onclick="return confirm('Are you sure want to delete ?')" 
                                                        data-toggle="tooltip" data-placement="top" title="DELETE" icon="delete" color="danger" />
                                                </form>                                                
                                            </td>
                                        </tr>
                                        @endforeach

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            @push('css')
            {{-- JQuery DataTable Css --}}
            <link href="{{ asset('ui/backend/assets/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css') }}" rel="stylesheet">
            @endpush

            @push('js')
            {{-- Jquery DataTable Plugin Js --}}
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/jquery.dataTables.js') }}"></script>
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js') }}"></script>
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js') }}"></script>
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/extensions/export/buttons.flash.min.js') }}"></script>
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/extensions/export/jszip.min.js') }}"></script>
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/extensions/export/pdfmake.min.js') }}"></script>
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/extensions/export/vfs_fonts.js') }}"></script>
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/extensions/export/buttons.html5.min.js') }}"></script>
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/extensions/export/buttons.print.min.js') }}"></script>
            {{-- Jquery DataTable --}}
            <script src="{{ asset('ui/backend/assets/js/pages/tables/jquery-datatable.js') }}"></script>

            {{-- Bootstrap Latest compiled and minified JavaScript --}}



            {{-- Show Tooltop on Buttons --}}
            <script>
                $(function() {
                    $('[data-toggle="tooltip"]').tooltip()
                })
            </script>

            @endpush

</x-backend.layout.master>

resources/views/admin/sizes/show.blade.php
<x-backend.layout.master>

    <x-slot:title>
        Size
        </x-slot>

        <x-slot:pageTitle>
            SIZE
            </x-slot>

            <div class="right_col" role="main">
                <div class="">
                    <div class="page-title">
                        <div class="title_left">
                            <h3 class="text-center">Show Size</h3>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="row">
                        <div class="col-md-12 col-sm-12 ">
                            <div class="x_panel">
                                <div class="x_title">
                                    <ul class="nav navbar-right panel_toolbox">
                                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                        </li>
                                        <li><a class="close-link"><i class="fa fa-close"></i></a>
                                        </li>
                                    </ul>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="x_content">
                                    <br />
                                    <div class="card text-center">
                                        <div class="card-header">
                                            Size - {{ $size->title }}
                                        </div>
                                        <div class="card-body">
                                            
                                            <x-utilities.link-list href="{{ route('admin.sizes.index') }}" color="info" text="Go to List" />
                                        
                                        </div>
                                        <div class="card-footer text-muted m-t-15">
                                            Created At - {{ $size->created_at }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

</x-backend.layout.master>