routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Public\OrderController;
use App\Http\Controllers\Admin\TagController;
use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\Admin\SizeController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\BrandController;
use App\Http\Controllers\Admin\ColorController;
use App\Http\Controllers\Public\CartController;
use App\Http\Controllers\Admin\CourseController;
use App\Http\Controllers\Admin\SliderController;
use App\Http\Controllers\Admin\CommentController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Public\PublicController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\DistrictController;
use App\Http\Controllers\Admin\DashboardController;

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';

Route::get('/', [PublicController::class, 'index'])->name('public.index');
Route::get('/shop', [PublicController::class, 'shop'])->name('public.shop');
// Route::get('/product', [PublicController::class, 'product'])->name('public.product');
Route::get('/category/{category}/products', [PublicController::class, 'categoryWiseProducts'])->name('public.categories.products');
Route::get('/products/{product}', [PublicController::class, 'productDetails'])->name('public.product_details');
Route::get('/cart', [PublicController::class, 'cart'])->name('public.cart');
//Route::get('/checkout', [PublicController::class, 'checkout'])->name('public.checkout');
//Route::get('/order', [PublicController::class, 'order'])->name('public.order');
Route::get('/about-us', [PublicController::class, 'aboutUs'])->name('public.about_us');

//cart routes
Route::get('/cart-items', [CartController::class, 'index'])->middleware('auth')->name('carts.index');
Route::post('products/{product}/cart', [CartController::class, 'store'])->middleware('auth')->name('public.carts.store');
Route::delete('cart-items/{cartItem}', [CartController::class, 'destroy'])->middleware('auth')->name('carts.destory');

//order routes
Route::get('/order-complete', [OrderController::class, 'index'])->name('orders.index');
Route::get('/checkout', [OrderController::class, 'create'])->middleware('auth')->name('orders.create');
Route::post('/orders', [OrderController::class, 'store'])->middleware('auth')->name('orders.store');


// ========Comment Route ==========
Route::post('/products/{product}/comments', [CommentController::class, 'store'])->name('products.comments.store')->middleware('auth');

//Route::get('/login', [AuthController::class, 'login'])->name('customer.login');

Route::prefix('admin')->name('admin.')->group(function () {

    Route::get('/', function () {
        return view('welcome');
    });

    Route::get('/dashboard', [DashboardController::class, 'index'])->middleware(['auth'])->name('dashboard.index');

    Route::get('/products', [ProductController::class, 'index'])->name('products.index');
    Route::get('/products/create', [ProductController::class, 'create'])->name('products.create');
    Route::post('/products', [ProductController::class, 'store'])->name('products.store');
    Route::get('/products/{product}', [ProductController::class, 'show'])->name('products.show');
    Route::get('/products/{product}/edit', [ProductController::class, 'edit'])->name('products.edit');
    Route::patch('/products/{product}', [ProductController::class, 'update'])->name('products.update');
    Route::delete('/products/{product}', [ProductController::class, 'destroy'])->name('products.destroy');


    Route::get('/categories/trash', [CategoryController::class, 'trash'])->name('categories.trash');
    Route::patch('/categories/trash/{id}', [CategoryController::class, 'restore'])->name('categories.restore');
    Route::delete('/categories/trash/{id}', [CategoryController::class, 'delete'])->name('categories.delete');
    Route::resource('categories', CategoryController::class);

    Route::get('/courses/trash', [CourseController::class, 'trash'])->name('courses.trash');
    Route::patch('/courses/trash/{id}', [CourseController::class, 'restore'])->name('courses.restore');
    Route::delete('/courses/trash/{id}', [CourseController::class, 'delete'])->name('courses.delete');
    Route::resource('courses', CourseController::class);
    Route::resource('/courses', CourseController::class);


    Route::resource('sizes', SizeController::class);
    Route::resource('tags', TagController::class);
    Route::resource('districts', DistrictController::class);
    Route::resource('brands', BrandController::class);
    Route::resource('colors', ColorController::class);
    ROute::resource('users', UserController::class);

    // ===============Slider==============

    Route::get('/sliders/trash', [SliderController::class, 'trash'])->name('sliders.trash');
    Route::patch('/sliders/trash/{id}', [SliderController::class, 'restore'])->name('sliders.restore');
    Route::delete('/sliders/trash/{id}', [SliderController::class, 'delete'])->name('sliders.delete');

    Route::resource('sliders', SliderController::class);
});

app/Models/Slider.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Slider extends Model
{
    use HasFactory, SoftDeletes;
    protected $guarded = [];

}

app/Http/Controllers/Admin/SliderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Category;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use App\Http\Controllers\Controller;
use App\Http\Requests\CategoryRequest;
use App\Models\Slider;
use Illuminate\Database\QueryException;
use Illuminate\Support\Facades\Storage;
use Image;

class SliderController extends Controller
{
    public function index()
    {
        $sliders = Slider::latest()->paginate(4);
        return view('admin.sliders.index', compact('sliders'));
    }

    public function create()
    {
        return view('admin.sliders.create');
    }

    public function store(Request $request)
    {
        $image = $request->file('image');

        if (file_exists($image)) {
            //make unique name for image
            $fileName  = date('dmY') . time() . '-' . uniqid() . '.' . $image->getClientOriginalExtension();

            if (!Storage::disk('public')->exists('sliders')) {
                Storage::disk('public')->makeDirectory('sliders');
            }

            //Storage::disk('public')->put('sliders/' . $fileName, file_get_contents($image));

            // used image intervention
            $categoryImage = Image::make($image)->resize(280, 280)->stream();

            Storage::disk('public')->put('sliders/' . $fileName, $categoryImage);
        }
        try {
            $slider = new Slider();
            $slider->title = $request->input('title');
            $slider->sub_title = $request->input('sub_title');
            $slider->content_position = $request->input('content_position');
            $slider->btn_text = $request->input('btn_text');
            $slider->btn_link = $request->input('btn_link');
            $slider->image_uri = $fileName ?? null;
            $slider->save();
            return redirect()->route('admin.sliders.index')->withMessage('Successfully Created');
        } catch (QueryException $e) {
            return redirect()->back()->withInput()->withErrors($e->getMessage());
        }
    }

    public function show(Slider $slider) //route model binding
    {
        // dd($category->products);
        
        return view('admin.sliders.show', compact('slider'));
    }

    public function edit(Slider $slider)
    {
        return view('admin.sliders.edit', compact('slider'));
    }

    public function update(Request $request, $id)
    {
        try {
            $slider = Slider::find($id);
            $slider->title = $request->input('title');
            $slider->sub_title = $request->input('sub_title');
            $slider->content_position = $request->input('content_position');
            $slider->btn_text = $request->input('btn_text');
            $slider->btn_link = $request->input('btn_link');
            $slider->image_uri = $fileName ?? $slider->image_url;
            $slider->save();
            return redirect()->route('admin.sliders.index')->withMessage('Successfully Created');
        } catch (QueryException $e) {
            return redirect()->back()->withInput()->withErrors($e->getMessage());
        }
    }

    public function destroy($id)
    {
        try {
            $slider = Slider::find($id);
            if ($slider->image_uri && file_exists(storage_path('app/public/sliders/' . $slider->image_uri) && $slider->image_url)) {
                unlink(storage_path('app/public/sliders/' . $slider->image_url));
            }

            $slider->delete();
            return redirect()->route('admin.sliders.index')->withMessage('Successfully Deleted');
        } catch (QueryException $e) {
            Log::error($e->getMessage());
            return redirect()->back()->withErrors($e->getMessage());
        }
    }

    public function trash()
    {
        $sliders = Slider::onlyTrashed()->paginate(2);
        return view('admin.sliders.trash', compact('sliders'));
    }

    public function restore($id)
    {
        try {
            $slider = Slider::onlyTrashed()->whereId($id)->firstOrFail();
            $slider->restore();
            return redirect()->back()->withMessage('Successfully Restored !');
        } catch (QueryException $e) {
            Log::error($e->getMessage());
            return redirect()->back()->withErrors($e->getMessage());
        }
    }

    public function delete($id)
    {
        try {
            $slider = Slider::onlyTrashed()->whereId($id)->firstOrFail();
            $slider->forceDelete();
            return redirect()->route('admin.sliders.index')->withMessage('Successfully Deleted');
        } catch (QueryException $e) {
            Log::error($e->getMessage());
            return redirect()->back()->withErrors($e->getMessage());
        }
    }

    public function uploadImage($file = null)
    {
        if (is_null($file)) return $file;

        $fileName = date('dmY') . time() . '.' . $file->getClientOriginalExtension();
        Image::make($file)
            ->resize(300, 200)
            ->save(storage_path('app/public/sliders/' . $fileName));
        return $fileName;
    }

    
}

resources/views/admin/sliders/create.blade.php
<x-backend.layout.master>

    <x-slot:title>
        Slider
        </x-slot>

        <x-slot:pageTitle>
            SLIDER
            </x-slot>

            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                ADD NEW SLIDER
                            </h2>
                        </div>
                        <div class="body">
                            <form class="form-horizontal" action="{{ route('admin.sliders.store') }}" method="POST"
                                enctype="multipart/form-data">
                                @csrf

                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">

                                        <x-forms.label for="title" text="title" />

                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line {{ $errors->has('title') ? 'focused error' : '' }}">

                                                <x-forms.input type="text" name="title"
                                                    value="{{ old('title') }}"
                                                    class=" @error('title') is-invalid @enderror" />

                                            </div>

                                            <x-alerts.error name="title" message="message" />

                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">

                                        <x-forms.label for="sub_title" text="sub title" />

                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line {{ $errors->has('sub_title') ? 'focused error' : '' }}">

                                                <x-forms.input type="text" name="sub_title"
                                                    value="{{ old('sub_title') }}"
                                                    class=" @error('sub_title') is-invalid @enderror" />

                                            </div>

                                            <x-alerts.error name="sub_title" message="message" />

                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">

                                        <x-forms.label for="content_position" text="content position" />

                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line {{ $errors->has('content_position') ? 'focused error' : '' }}">

                                                <x-forms.input type="text" name="content_position"
                                                    value="{{ old('content_position') }}"
                                                    class=" @error('content_position') is-invalid @enderror" />

                                            </div>

                                            <x-alerts.error name="content_position" message="message" />

                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">

                                        <x-forms.label for="btn_text" text="btn text" />

                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line {{ $errors->has('btn_text') ? 'focused error' : '' }}">

                                                <x-forms.input type="text" name="btn_text"
                                                    value="{{ old('btn_text') }}"
                                                    class=" @error('btn_text') is-invalid @enderror" />

                                            </div>

                                            <x-alerts.error name="btn_link" message="message" />

                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">

                                        <x-forms.label for="btn_link" text="btn link" />

                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line {{ $errors->has('btn_link') ? 'focused error' : '' }}">

                                                <x-forms.input type="text" name="btn_link"
                                                    value="{{ old('btn_link') }}"
                                                    class=" @error('btn_link') is-invalid @enderror" />

                                            </div>

                                            <x-alerts.error name="btn_text" message="message" />

                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">

                                        <x-forms.label for="image" text="image" />

                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line {{ $errors->has('image') ? 'focused error' : '' }}">

                                                <x-forms.input type="file" name="image"
                                                    class=" @error('image') is-invalid @enderror" />

                                            </div>

                                            <x-alerts.error name="image" message="message" />

                                        </div>
                                    </div>
                                </div>
                                
                                {{-- <div class="row clearfix">
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7 col-lg-offset-2 col-md-offset-2">
                                        <div class="form-group">

                                            <x-forms.checkbox name="is_active" text="is active" checked="" />

                                        </div>
                                    </div>
                                </div> --}}

                                <div class="row clearfix">
                                    <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">

                                        <x-utilities.link-list href="{{ route('admin.sliders.index') }}"
                                            color="danger" text="back" />

                                        <x-forms.button class="m-t-15" color="primary" text="submit" />

                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

</x-backend.layout.master>

resources/views/admin/sliders/edit.blade.php
<x-backend.layout.master>

    <x-slot:title>
        Slider
        </x-slot>

        <x-slot:pageTitle>
            SLIDER
            </x-slot>

            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                ADD NEW SLIDER
                            </h2>
                        </div>
                        <div class="body">
                            <form class="form-horizontal" action="{{ route('admin.sliders.update', $slider->id) }}" method="POST"
                                enctype="multipart/form-data">
                                @csrf
                                @method('patch')

                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">

                                        <x-forms.label for="title" text="title" />

                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line {{ $errors->has('title') ? 'focused error' : '' }}">

                                                <x-forms.input type="text" name="title"
                                                    value="{{ old('title',$slider->title) }}"
                                                    class=" @error('title') is-invalid @enderror" />

                                            </div>

                                            <x-alerts.error name="title" message="message" />

                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">

                                        <x-forms.label for="sub_title" text="sub title" />

                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line {{ $errors->has('sub_title') ? 'focused error' : '' }}">

                                                <x-forms.input type="text" name="sub_title"
                                                    value="{{ old('sub_title',$slider->sub_title) }}"
                                                    class=" @error('sub_title') is-invalid @enderror" />

                                            </div>

                                            <x-alerts.error name="sub_title" message="message" />

                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">

                                        <x-forms.label for="content_position" text="content position" />

                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line {{ $errors->has('content_position') ? 'focused error' : '' }}">

                                                <x-forms.input type="text" name="content_position"
                                                    value="{{ old('content_position',$slider->content_position) }}"
                                                    class=" @error('content_position') is-invalid @enderror" />

                                            </div>

                                            <x-alerts.error name="content_position" message="message" />

                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">

                                        <x-forms.label for="btn_text" text="btn text" />

                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line {{ $errors->has('btn_text') ? 'focused error' : '' }}">

                                                <x-forms.input type="text" name="btn_text"
                                                    value="{{ old('btn_text',$slider->btn_text) }}"
                                                    class=" @error('btn_text') is-invalid @enderror" />

                                            </div>

                                            <x-alerts.error name="btn_link" message="message" />

                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">

                                        <x-forms.label for="btn_link" text="btn link" />

                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line {{ $errors->has('btn_link') ? 'focused error' : '' }}">

                                                <x-forms.input type="text" name="btn_link"
                                                    value="{{ old('btn_link',$slider->btn_link) }}"
                                                    class=" @error('btn_link') is-invalid @enderror" />

                                            </div>

                                            <x-alerts.error name="btn_text" message="message" />

                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">

                                        <x-forms.label for="image" text="image" />

                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line {{ $errors->has('image') ? 'focused error' : '' }}">

                                                <x-forms.input type="file" name="image"
                                                    class=" @error('image') is-invalid @enderror" />

                                            </div>

                                            <x-alerts.error name="image" message="message" />

                                        </div>
                                    </div>
                                </div>
                                
                                {{-- <div class="row clearfix">
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7 col-lg-offset-2 col-md-offset-2">
                                        <div class="form-group">

                                            <x-forms.checkbox name="is_active" text="is active" checked="" />

                                        </div>
                                    </div>
                                </div> --}}

                                <div class="row clearfix">
                                    <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">

                                        <x-utilities.link-list href="{{ route('admin.sliders.index') }}"
                                            color="danger" text="back" />

                                        <x-forms.button class="m-t-15" color="primary" text="update" />

                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

</x-backend.layout.master>

resources/views/admin/sliders/trash.blade.php
<x-backend.layout.master>
    <x-slot:title>
        Slider
    </x-slot:title>

    <x-slot:pageTitle>
        Sliders
    </x-slot:pageTitle>

    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Slider Trash List
            <a class="btn btn-sm btn-primary" href="{{ route('admin.sliders.index') }}">List</a>
        </div>
        <div class="card-body">

            {{-- @if ($errors->any())
                <x-admin.alerts.errors />
            @endif --}}

            <x-alerts.message type="success" :message="session('message')" />

            <table class="table">
                <thead>
                    <tr>
                        <th>SL#</th>
                        <th>Title</th>
                        <th>Sub Title</th>
                        <th>Button Text</th>
                        <th>image</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($sliders as $slider)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $slider->title }}</td>
                            <td>{{ $slider->sub_title }}</td>
                            <td>{{ $slider->btn_text }}</td>
                            <td class="align-center"><img src="{{ asset('storage/sliders/' . $slider->image_uri) }}"
                                    alt="{{ $slider->title }}" width="50" height="50">
                            </td>
                            <td>

                                <form method="post"
                                    action="{{ route('admin.sliders.restore', ['id' => $slider->id]) }}"
                                    style="display:inline">
                                    @csrf
                                    @method('patch')
                                    <x-forms.button color="warning"
                                        onclick="return confirm('Are you sure want to restore?')" text="Restore" />
                                </form>


                                <form method="post" action="{{ route('admin.sliders.delete', ['id' => $slider->id]) }}"
                                    style="display:inline">
                                    @csrf
                                    @method('delete')
                                    <x-forms.button color="danger"
                                        onclick="return confirm('Are you sure want to delete permanently?')"
                                        text="Delete" />
                                </form>


                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>

            {{ $sliders->links() }}

        </div>
    </div>

    {{-- page specific css --}}
    @push('css')
    @endpush

    {{-- page specific js --}}
    @push('js')
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
        <script src="{{ asset('ui/backend') }}/js/datatables-simple-demo.js"></script>
    @endpush

</x-backend.layout.master>