routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Public\OrderController;
use App\Http\Controllers\Admin\TagController;
use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\Admin\SizeController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\BrandController;
use App\Http\Controllers\Admin\ColorController;
use App\Http\Controllers\Public\CartController;
use App\Http\Controllers\Admin\CourseController;
use App\Http\Controllers\Admin\SliderController;
use App\Http\Controllers\Admin\CommentController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Public\PublicController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\DistrictController;
use App\Http\Controllers\Admin\DashboardController;

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';

Route::get('/', [PublicController::class, 'index'])->name('public.index');
Route::get('/shop', [PublicController::class, 'shop'])->name('public.shop');
// Route::get('/product', [PublicController::class, 'product'])->name('public.product');
Route::get('/category/{category}/products', [PublicController::class, 'categoryWiseProducts'])->name('public.categories.products');
Route::get('/products/{product}', [PublicController::class, 'productDetails'])->name('public.product_details');
Route::get('/cart', [PublicController::class, 'cart'])->name('public.cart');
//Route::get('/checkout', [PublicController::class, 'checkout'])->name('public.checkout');
//Route::get('/order', [PublicController::class, 'order'])->name('public.order');
Route::get('/about-us', [PublicController::class, 'aboutUs'])->name('public.about_us');

//cart routes
Route::get('/cart-items', [CartController::class, 'index'])->middleware('auth')->name('carts.index');
Route::post('products/{product}/cart', [CartController::class, 'store'])->middleware('auth')->name('public.carts.store');
Route::delete('cart-items/{cartItem}', [CartController::class, 'destroy'])->middleware('auth')->name('carts.destory');

//order routes
Route::get('/order-complete', [OrderController::class, 'index'])->name('orders.index');
Route::get('/checkout', [OrderController::class, 'create'])->middleware('auth')->name('orders.create');
Route::post('/orders', [OrderController::class, 'store'])->middleware('auth')->name('orders.store');


// ========Comment Route ==========
Route::post('/products/{product}/comments', [CommentController::class, 'store'])->name('products.comments.store')->middleware('auth');

//Route::get('/login', [AuthController::class, 'login'])->name('customer.login');

Route::prefix('admin')->name('admin.')->group(function () {

    Route::get('/', function () {
        return view('welcome');
    });

    Route::get('/dashboard', [DashboardController::class, 'index'])->middleware(['auth'])->name('dashboard.index');

    Route::get('/products', [ProductController::class, 'index'])->name('products.index');
    Route::get('/products/create', [ProductController::class, 'create'])->name('products.create');
    Route::post('/products', [ProductController::class, 'store'])->name('products.store');
    Route::get('/products/{product}', [ProductController::class, 'show'])->name('products.show');
    Route::get('/products/{product}/edit', [ProductController::class, 'edit'])->name('products.edit');
    Route::patch('/products/{product}', [ProductController::class, 'update'])->name('products.update');
    Route::delete('/products/{product}', [ProductController::class, 'destroy'])->name('products.destroy');


    Route::get('/categories/trash', [CategoryController::class, 'trash'])->name('categories.trash');
    Route::patch('/categories/trash/{id}', [CategoryController::class, 'restore'])->name('categories.restore');
    Route::delete('/categories/trash/{id}', [CategoryController::class, 'delete'])->name('categories.delete');
    Route::resource('categories', CategoryController::class);

    Route::get('/courses/trash', [CourseController::class, 'trash'])->name('courses.trash');
    Route::patch('/courses/trash/{id}', [CourseController::class, 'restore'])->name('courses.restore');
    Route::delete('/courses/trash/{id}', [CourseController::class, 'delete'])->name('courses.delete');
    Route::resource('courses', CourseController::class);
    Route::resource('/courses', CourseController::class);


    Route::resource('sizes', SizeController::class);
    Route::resource('tags', TagController::class);
    Route::resource('districts', DistrictController::class);
    Route::resource('brands', BrandController::class);
    Route::resource('colors', ColorController::class);
    ROute::resource('users', UserController::class);

    // ===============Slider==============

    Route::get('/sliders/trash', [SliderController::class, 'trash'])->name('sliders.trash');
    Route::patch('/sliders/trash/{id}', [SliderController::class, 'restore'])->name('sliders.restore');
    Route::delete('/sliders/trash/{id}', [SliderController::class, 'delete'])->name('sliders.delete');

    Route::resource('sliders', SliderController::class);
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'role_id',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function role()
    {
        return $this->belongsTo(Role::class);
    }

    public function cart()
    {
        return $this->hasOne(Cart::class);
    }

    public function orders()
    {
        return $this->hasMany(Order::class, 'ordered_by');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\UserRequest;
use App\Models\Role;
use App\Models\User;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $this->authorize('user-list');
        $users = User::with('role')->latest()->get();
        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {     
        $this->authorize('user-list');
        return view('admin.users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequest $request, User $user)
    {
       
        try {
            $user->update([
                'name' => $request->name,
                'email' => $request->email,
                'role_id' => $request->role_id
            ]);

            return redirect()->route('admin.users.index')->with('message', 'User Successfully Updated !');
        } catch (QueryException $e) {
            Log::error($e->getMessage());
            return redirect()->back()->withInput()->withError($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // $this->authorize('user-delete', $user);
    }
}

app/View/Components/SelectRole.php
<?php

namespace App\View\Components;

use App\Models\Role;
use Illuminate\View\Component;

class SelectRole extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */

    public $options, $name;

    public function __construct($name = null)
    {
        $this->name = $name;
        $this->options = $this->getOptions();
    }

    public function getOptions()
    {
        $options = [];
        
        foreach(Role::all() as $role){
            $options[] = ['id' => $role->id, 'value' => $role->role];
        }

        return $options;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.forms.select');
    }
}

resources/views/admin/users/edit.blade.php
<x-backend.layout.master>

    <x-slot:title>
        User
        </x-slot>

        <x-slot:pageTitle>
            USER
            </x-slot>

            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                EDIT USER
                            </h2>
                        </div>
                        <div class="body">
                            <form class="form-horizontal" action="{{ route('admin.users.update', $user->id) }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                @method('PATCH')

                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">

                                        <x-forms.label for="name" text="name" />

                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line {{ $errors->has('name') ? 'focused error' : '' }}">

                                                <x-forms.input type="text" name="name" value="{{ old('name', $user->name) }}" class=" @error('name') is-invalid @enderror" />

                                            </div>

                                            <x-alerts.error name="name" message="message" />

                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">

                                        <x-forms.label for="email" text="email" />

                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line {{ $errors->has('email') ? 'focused error' : '' }}">

                                                <x-forms.input type="text" name="email" value="{{ old('email', $user->email) }}" class=" @error('email') is-invalid @enderror" />

                                            </div>

                                            <x-alerts.error name="email" message="message" />

                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">

                                        <x-forms.label for="role" text="Role" />

                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">

                                            {{-- <x-forms.select name="role_id">
                                                <x-slot:option>
                                                    <option value="" disabled selected>Select Role Type</option>
                                                    @foreach ($roles as $role)
                                                    <option value="{{ $role->id }}" {{ $role->id == $user->role_id ? 'selected' : ''}}>{{ $role->role }}</option>
                                                    @endforeach
                                                </x-slot:option>
                                            </x-forms.select> --}}

                                            <x-select-role name="role_id" text="role" :selected="$user->role_id"/>

                                            <x-alerts.error name="role" message="message" />

                                        </div>
                                    </div>

                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">

                                        <x-utilities.link-list href="{{ route('admin.users.index') }}" color="danger" text="back" />

                                        <x-forms.button class="m-t-15" color="primary" text="update" />

                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            @push('css')
            {{-- Bootstrap Select Css --}}
            <link href="{{ asset('ui/backend/assets/plugins/bootstrap-select/css/bootstrap-select.css') }}" rel="stylesheet" />
            @endpush

            @push('js')
            {{-- Select Plugin Js --}}
            <script src="{{ asset('ui/backend/assets/plugins/bootstrap-select/js/bootstrap-select.js') }}"></script>
            @endpush

</x-backend.layout.master>

resources/views/admin/users/index.blade.php
<x-backend.layout.master>

    <x-slot:title>
        User
        </x-slot>

        <x-slot:pageTitle>
            USER
            </x-slot>

            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                ALL USERS
                                <x-utilities.link-create href="{{ route('admin.users.create') }}" class="pull-right m-r-5" btnType="success" text="Add New User" icon="add" />

                            </h2><br>
                        <x-alerts.message id="cateroryId" class="text-white" type="success" :message="session('message')" />
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                <thead>
                                    <tr>
                                        <th>Sl</th>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Role</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>Sl</th>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Role</th>
                                        <th>Action</th>
                                    </tr>
                                </tfoot>
                                <tbody>
                                    @foreach ($users as $user)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $user->name }}</td>
                                        <td>{{ $user->email }}</td>
                                        <td>{{ $user->role->name }}</td>
                                        <td class="text-center" style="white-space:nowrap;">
                                            <x-utilities.link-show href="{{ route('admin.users.show', $user->id) }}" text="SHOW" />
                                           
                                            
                                            <x-utilities.link-edit href="{{ route('admin.users.edit', $user->id) }}" text="EDIT" />
                                           
                                            <form action="{{ route('admin.users.destroy', $user->id) }}" method="POST" style="display:inline">
                                                @csrf
                                                @method('DELETE')
                                                <x-forms.button onclick="return confirm('Are you sure want to delete ?')" data-toggle="tooltip" data-placement="top" title="TRASH" icon="delete" color="danger" />
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            </div>

            @push('css')
            {{-- JQuery DataTable Css --}}
            <link href="{{ asset('ui/backend/assets/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css') }}" rel="stylesheet">
            @endpush

            @push('js')
            {{-- Jquery DataTable Plugin Js --}}
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/jquery.dataTables.js') }}"></script>
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js') }}"></script>
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js') }}"></script>
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/extensions/export/buttons.flash.min.js') }}"></script>
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/extensions/export/jszip.min.js') }}"></script>
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/extensions/export/pdfmake.min.js') }}"></script>
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/extensions/export/vfs_fonts.js') }}"></script>
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/extensions/export/buttons.html5.min.js') }}"></script>
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/extensions/export/buttons.print.min.js') }}"></script>
            {{-- Jquery DataTable --}}
            <script src="{{ asset('ui/backend/assets/js/pages/tables/jquery-datatable.js') }}"></script>

            {{-- Bootstrap Latest compiled and minified JavaScript --}}



            {{-- Show Tooltop on Buttons --}}
            <script>
                $(function() {
                    $('[data-toggle="tooltip"]').tooltip()
                })
            </script>

            @endpush

</x-backend.layout.master>

resources/views/admin/users/show.blade.php
<x-backend.layout.master>

    <x-slot:title>
        Course
        </x-slot>

        <x-slot:pageTitle>
            COURSE
            </x-slot>

            <div class="right_col" role="main">
                <div class="">
                    <div class="page-title">
                        <div class="title_left">
                            <h3 class="text-center">Show Course</h3>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="row">
                        <div class="col-md-12 col-sm-12 ">
                            <div class="x_panel">
                                <div class="x_title">
                                    <ul class="nav navbar-right panel_toolbox">
                                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                        </li>
                                        <li><a class="close-link"><i class="fa fa-close"></i></a>
                                        </li>
                                    </ul>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="x_content">
                                    <br />
                                    <div class="card text-center">
                                        <div class="card-header">
                                            Course - {{ $course->title }}
                                        </div>
                                        <div class="card-body">
                                            <h5 class="card-title">{{ $course->course_type }}</h5>
                                            <div class="row clearfix">
                                                <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7 col-lg-offset-1 col-md-offset-1">
                                                    <div class="form-group">

                                                        <img src="{{ asset('storage/courses/'.$course->banner) }}" alt="{{ $course->title }}" height="200px;">

                                                    </div>
                                                </div>
                                            </div>
                                            {{-- <a class="btn btn-primary" href="{{ route('admin.courses.index') }}">Go to List</a> --}}
                                            <x-utilities.link-list href="{{ route('admin.courses.index') }}" color="info" text="Go to List" />
                                        </div>
                                        <div class="card-footer text-muted m-t-15">
                                            Created At - {{ $course->created_at }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

</x-backend.layout.master>

resources/views/admin/users/trash.blade.php
<x-backend.layout.master>

    <x-slot:title>
        Course
        </x-slot>

        <x-slot:pageTitle>
            COURSE
            </x-slot>

            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                ALL DELETED COURSES
                                {{-- <a class="btn btn-success waves-effect pull-right" href="{{ route('admin.categories.create') }}">
                                <i class="material-icons">add</i>
                                <span>Add New Category</span>
                                </a> --}}
                                <x-utilities.link-create href="{{ route('admin.courses.index') }}" btnType="success pull-right" text="Course List" icon="list" />

                            </h2><br>
                            {{-- @if(request()->session()->has('message'))
                                <div class="alert alert-success m-5" role="alert">
                                    {{ session('message') }}
                        </div>
                        @endif --}}
                        <x-alerts.message id="courseId" class="text-white" type="success" :message="session('message')" />
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                <thead>
                                    <tr>
                                        <th>Sl</th>
                                        <th>Title</th>
                                        <th>Batch No</th>
                                        <th>Course Type</th>
                                        <th>Class Start Date</th>
                                        <th>Class End Date</th>
                                        <th>Instructor Name</th>
                                        <th>Banner</th>
                                        <th>Status</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>Sl</th>
                                        <th>Title</th>
                                        <th>Batch No</th>
                                        <th>Course Type</th>
                                        <th>Class Start Date</th>
                                        <th>Class End Date</th>
                                        <th>Instructor Name</th>
                                        <th>Banner</th>
                                        <th>Status</th>
                                        <th>Action</th>
                                    </tr>
                                </tfoot>
                                <tbody>
                                    @foreach ($courses as $course)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $course->title }}</td>
                                        <td>{{ $course->batch_no }}</td>
                                        <td>{{ $course->course_type }}</td>
                                        <td>{{ Carbon\Carbon::parse($course->course_start_date)->format('d-m-Y') }}</td>
                                        <td>{{ Carbon\Carbon::parse($course->course_end_date)->format('d-m-Y') }}</td>
                                        <td>{{ $course->instructor_name }}</td>
                                        <td class="align-center"><img src="{{ asset('storage/courses/'.$course->banner) }}" alt="{{ $course->title }}" width="50" height="50"></td>
                                        <td><span class="badge {{ $course->is_active ? 'bg-green' : 'bg-pink' }}">{{ $course->is_active ? 'Active' : 'Inactive' }}</span></td>
                                        <td class="text-center" style="white-space:nowrap;">
                                            <form action="{{ route('admin.courses.restore', $course->id) }}" method="POST" style="display:inline">
                                                @csrf
                                                @method('PATCH')
                                                <x-forms.button onclick="return confirm('Are you sure want to restore ?')" data-toggle="tooltip" data-placement="top" title="RESTORE" icon="restore_from_trash" color="warning" />
                                            </form>
                                            <form action="{{ route('admin.courses.delete', $course->id) }}" method="POST" style="display:inline">
                                                @csrf
                                                @method('DELETE')
                                                <x-forms.button onclick="return confirm('Are you sure want to delete permanently ?')" data-toggle="tooltip" data-placement="top" title="DELETE" icon="delete_forever" color="danger" />
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            </div>

            @push('css')
            {{-- JQuery DataTable Css --}}
            <link href="{{ asset('ui/backend/assets/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css') }}" rel="stylesheet">
            @endpush

            @push('js')
            {{-- Jquery DataTable Plugin Js --}}
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/jquery.dataTables.js') }}"></script>
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js') }}"></script>
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js') }}"></script>
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/extensions/export/buttons.flash.min.js') }}"></script>
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/extensions/export/jszip.min.js') }}"></script>
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/extensions/export/pdfmake.min.js') }}"></script>
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/extensions/export/vfs_fonts.js') }}"></script>
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/extensions/export/buttons.html5.min.js') }}"></script>
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/extensions/export/buttons.print.min.js') }}"></script>
            {{-- Jquery DataTable --}}
            <script src="{{ asset('ui/backend/assets/js/pages/tables/jquery-datatable.js') }}"></script>

            {{-- Bootstrap Latest compiled and minified JavaScript --}}



            {{-- Show Tooltop on Buttons --}}
            <script>
                $(function() {
                    $('[data-toggle="tooltip"]').tooltip()
                })
            </script>

            @endpush

</x-backend.layout.master>