routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Public\OrderController;
use App\Http\Controllers\Admin\TagController;
use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\Admin\SizeController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\BrandController;
use App\Http\Controllers\Admin\ColorController;
use App\Http\Controllers\Public\CartController;
use App\Http\Controllers\Admin\CourseController;
use App\Http\Controllers\Admin\SliderController;
use App\Http\Controllers\Admin\CommentController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Public\PublicController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\DistrictController;
use App\Http\Controllers\Admin\DashboardController;

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';

Route::get('/', [PublicController::class, 'index'])->name('public.index');
Route::get('/shop', [PublicController::class, 'shop'])->name('public.shop');
// Route::get('/product', [PublicController::class, 'product'])->name('public.product');
Route::get('/category/{category}/products', [PublicController::class, 'categoryWiseProducts'])->name('public.categories.products');
Route::get('/products/{product}', [PublicController::class, 'productDetails'])->name('public.product_details');
Route::get('/cart', [PublicController::class, 'cart'])->name('public.cart');
//Route::get('/checkout', [PublicController::class, 'checkout'])->name('public.checkout');
//Route::get('/order', [PublicController::class, 'order'])->name('public.order');
Route::get('/about-us', [PublicController::class, 'aboutUs'])->name('public.about_us');

//cart routes
Route::get('/cart-items', [CartController::class, 'index'])->middleware('auth')->name('carts.index');
Route::post('products/{product}/cart', [CartController::class, 'store'])->middleware('auth')->name('public.carts.store');
Route::delete('cart-items/{cartItem}', [CartController::class, 'destroy'])->middleware('auth')->name('carts.destory');

//order routes
Route::get('/order-complete', [OrderController::class, 'index'])->name('orders.index');
Route::get('/checkout', [OrderController::class, 'create'])->middleware('auth')->name('orders.create');
Route::post('/orders', [OrderController::class, 'store'])->middleware('auth')->name('orders.store');


// ========Comment Route ==========
Route::post('/products/{product}/comments', [CommentController::class, 'store'])->name('products.comments.store')->middleware('auth');

//Route::get('/login', [AuthController::class, 'login'])->name('customer.login');

Route::prefix('admin')->name('admin.')->group(function () {

    Route::get('/', function () {
        return view('welcome');
    });

    Route::get('/dashboard', [DashboardController::class, 'index'])->middleware(['auth'])->name('dashboard.index');

    Route::get('/products', [ProductController::class, 'index'])->name('products.index');
    Route::get('/products/create', [ProductController::class, 'create'])->name('products.create');
    Route::post('/products', [ProductController::class, 'store'])->name('products.store');
    Route::get('/products/{product}', [ProductController::class, 'show'])->name('products.show');
    Route::get('/products/{product}/edit', [ProductController::class, 'edit'])->name('products.edit');
    Route::patch('/products/{product}', [ProductController::class, 'update'])->name('products.update');
    Route::delete('/products/{product}', [ProductController::class, 'destroy'])->name('products.destroy');


    Route::get('/categories/trash', [CategoryController::class, 'trash'])->name('categories.trash');
    Route::patch('/categories/trash/{id}', [CategoryController::class, 'restore'])->name('categories.restore');
    Route::delete('/categories/trash/{id}', [CategoryController::class, 'delete'])->name('categories.delete');
    Route::resource('categories', CategoryController::class);

    Route::get('/courses/trash', [CourseController::class, 'trash'])->name('courses.trash');
    Route::patch('/courses/trash/{id}', [CourseController::class, 'restore'])->name('courses.restore');
    Route::delete('/courses/trash/{id}', [CourseController::class, 'delete'])->name('courses.delete');
    Route::resource('courses', CourseController::class);
    Route::resource('/courses', CourseController::class);


    Route::resource('sizes', SizeController::class);
    Route::resource('tags', TagController::class);
    Route::resource('districts', DistrictController::class);
    Route::resource('brands', BrandController::class);
    Route::resource('colors', ColorController::class);
    ROute::resource('users', UserController::class);

    // ===============Slider==============

    Route::get('/sliders/trash', [SliderController::class, 'trash'])->name('sliders.trash');
    Route::patch('/sliders/trash/{id}', [SliderController::class, 'restore'])->name('sliders.restore');
    Route::delete('/sliders/trash/{id}', [SliderController::class, 'delete'])->name('sliders.delete');

    Route::resource('sliders', SliderController::class);
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Category extends Model
{
    use HasFactory, SoftDeletes;

    protected $guarded = [];

    public function products()
    {
        return $this->belongsToMany(Product::class);
    }

    // query scope
    public function scopeActive($query){
        return $query->where('is_active', true);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Category;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use App\Http\Controllers\Controller;
use Intervention\Image\Facades\Image;
use App\Http\Requests\CategoryRequest;
use Illuminate\Database\QueryException;
use Illuminate\Support\Facades\Storage;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $this->authorize('category-list');

        $categories = Category::latest()->get();

        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        $image = $request->file('image');
        $slug = Str::slug($request->title);

        if (file_exists($image)) {
            //make unique name for image
            $fileName  = $slug . '-' . date('dmY') . time() . '-' . uniqid() . '.' . $image->getClientOriginalExtension();

            if (!Storage::disk('public')->exists('categories')) {
                Storage::disk('public')->makeDirectory('categories');
            }

            //Storage::disk('public')->put('categories/' . $fileName, file_get_contents($image));

            // used image intervention
            $categoryImage = Image::make($image)->resize(280, 280)->stream();

            Storage::disk('public')->put('categories/' . $fileName, $categoryImage);
        }

        try {
            Category::create([
                'title' => $request->title,
                'slug' => $slug,
                'description' => $request->description,
                'image' => $fileName ?? null,
                'is_active' => $request->is_active ?? false
            ]);

            // return redirect()->route('admin.categories.index')->with('message', 'Category Successfully Saved !');
            return redirect()->route('admin.categories.index')->withMessage('Category Successfully Created !');
        } catch (QueryException $e) {

            return redirect()->back()->withInput()->withError($e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        // $category = Category::findOrFail($category);
        $this->authorize('category-list');

        return view('admin.categories.show', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        // $category = Category::findOrFail($category);
        $this->authorize('category-list');

        return view('admin.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request, Category $category)
    {
        // $category = Category::findOrFail($category);

        // $request->validate([
        //     'title' => 'required|min:3|max:15|unique:categories,title,' . $category->id 
        // ]);
        $this->authorize('category-list');
        
        $image = $request->file('image');
        $slug = Str::slug($request->title);

        if (file_exists($image)) {
            //make unique name for image
            $fileName  = $slug . '-' . date('dmY') . time() . '-' . uniqid() . '.' . $image->getClientOriginalExtension();

            if (!Storage::disk('public')->exists('categories')) {
                Storage::disk('public')->makeDirectory('categories');
            }

            //delete old category image
            if (Storage::disk('public')->exists('categories/' . $category->image)) {
                Storage::disk('public')->delete('categories/' . $category->image);
            }

            //Storage::disk('public')->put('categories/' . $fileName, file_get_contents($image));

            // used image intervention
            $categoryImage = Image::make($image)->resize(280, 280)->stream();

            Storage::disk('public')->put('categories/' . $fileName, $categoryImage);
        }

        try {
            $category->update([
                'title' => $request->title,
                'slug' => $slug,
                'description' => $request->description,
                'image' => $fileName ?? $category->image,
                'is_active' => $request->is_active ?? false
            ]);

            return redirect()->route('admin.categories.index')->with('message', 'Category Successfully Updated !');
        } catch (QueryException $e) {

            return redirect()->back()->withInput()->withError($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        // $category = Category::findOrFail($category);
        $this->authorize('category-list');
        try {

            // $this->authorize('category-delete', $category);

            $category->delete();

            return redirect()->route('admin.categories.index')->with('message', 'Category Successfully Trashed !');
        } catch (QueryException $e) {

            return redirect()->back()->withInput()->withError($e->getMessage());
        }
    }

    public function trash()
    {
        $categories = Category::onlyTrashed()->get();
        return view('admin.categories.trash', compact('categories'));
    }

    public function restore($id)
    {
        try {
            $category = Category::onlyTrashed()->whereId($id)->firstOrFail();
            $category->restore();
            return redirect()->back()->withMessage('Category Successfully Restored !');
        } catch (QueryException $e) {
            Log::error($e->getMessage());
            return redirect()->back()->withErrors($e->getMessage());
        }
    }

    public function delete($id)
    {
        $category = Category::onlyTrashed()->whereId($id)->firstOrFail();

        if (Storage::disk('public')->exists('categories/' . $category->image)) {
            Storage::disk('public')->delete('categories/' . $category->image);
        }

        try {
            $category->forceDelete();
            return redirect()->back()->withMessage('Category Successfully Deleted');
        } catch (QueryException $e) {
            Log::error($e->getMessage());
            return redirect()->back()->withErrors($e->getMessage());
        }
    }
}

resources/views/admin/categories/create.blade.php
<x-backend.layout.master>

    <x-slot:title>
        Category
        </x-slot>

        <x-slot:pageTitle>
            CATEGORY
            </x-slot>

            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                ADD NEW CATEGORY
                            </h2>
                        </div>
                        <div class="body">
                            <form class="form-horizontal" action="{{ route('admin.categories.store') }}" method="POST"
                                enctype="multipart/form-data">
                                @csrf

                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">

                                        <x-forms.label for="title" text="title" />

                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line {{ $errors->has('title') ? 'focused error' : '' }}">

                                                <x-forms.input type="text" name="title"
                                                    value="{{ old('title') }}"
                                                    class=" @error('title') is-invalid @enderror" />

                                            </div>

                                            <x-alerts.error name="title" message="message" />

                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">

                                        <x-forms.label for="image" text="image" />

                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line {{ $errors->has('image') ? 'focused error' : '' }}">

                                                <x-forms.input type="file" name="image"
                                                    class=" @error('image') is-invalid @enderror" />

                                            </div>

                                            <x-alerts.error name="image" message="message" />

                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">

                                        <x-forms.label for="description" text="description" />

                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div
                                                class="form-line {{ $errors->has('description') ? 'focused error' : '' }}">

                                                <x-forms.textarea class="@error('description') is-invalid @enderror"
                                                    name="description" value="{{ old('description') }}" />

                                            </div>

                                            <x-alerts.error name="description" message="message" />

                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7 col-lg-offset-2 col-md-offset-2">
                                        <div class="form-group">

                                            <x-forms.checkbox name="is_active" text="is active" checked="" />

                                        </div>
                                    </div>
                                </div>

                                <div class="row clearfix">
                                    <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">

                                        <x-utilities.link-list href="{{ route('admin.categories.index') }}"
                                            color="danger" text="back" />

                                        <x-forms.button class="m-t-15" color="primary" text="submit" />

                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

</x-backend.layout.master>

resources/views/admin/categories/edit.blade.php
<x-backend.layout.master>

    <x-slot:title>
        Category
        </x-slot>

        <x-slot:pageTitle>
            CATEGORY
            </x-slot>

            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                EDIT CATEGORY
                            </h2>
                        </div>
                        <div class="body">
                            <form class="form-horizontal" action="{{ route('admin.categories.update',  $category->id) }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                @method('PATCH')

                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">

                                        <x-forms.label for="title" text="title" />

                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line {{ $errors->has('title') ? 'focused error' : '' }}">

                                                <x-forms.input type="text" name="title" value="{{ old('title', $category->title) }}" class=" @error('title') is-invalid @enderror" />

                                            </div>

                                            <x-alerts.error name="title" message="message" />

                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7 col-lg-offset-2 col-md-offset-2">
                                        <div class="form-group">

                                            <img src="{{ asset('storage/categories/'.$category->image) }}" alt="{{ $category->title }}" height="200px;">

                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">

                                        <x-forms.label for="image" text="image" />

                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line {{ $errors->has('image') ? 'focused error' : '' }}">

                                                <x-forms.input type="file" name="image" class=" @error('image') is-invalid @enderror" />

                                            </div>

                                            <x-alerts.error name="image" message="message" />

                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">

                                        <x-forms.label for="description" text="description" />

                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line {{ $errors->has('description') ? 'focused error' : '' }}">

                                                <x-forms.textarea class="@error('description') is-invalid @enderror" name="description" value="{{ old('description', $category->description) }}" />

                                            </div>

                                            <x-alerts.error name="description" message="message" />

                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7 col-lg-offset-2 col-md-offset-2">
                                        <div class="form-group">

                                            <x-forms.checkbox name="is_active" text="is active" checked="{{ $category->is_active ? 'checked' : '' }}" />

                                        </div>
                                    </div>
                                </div>

                                <div class="row clearfix">
                                    <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">
                                        <x-utilities.link-list href="{{ route('admin.categories.index') }}" color="danger" text="back" />
                                        <x-forms.button class="m-t-15" color="primary" text="update" />
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

</x-backend.layout.master>

resources/views/admin/categories/trash.blade.php
<x-backend.layout.master>

    <x-slot:title>
        Category
        </x-slot>

        <x-slot:pageTitle>
            CATEGORY
            </x-slot>

            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                ALL DELETED CATEGORIES
                                {{--  <a class="btn btn-success waves-effect pull-right" href="{{ route('admin.categories.create') }}">
                                    <i class="material-icons">add</i>
                                    <span>Add New Category</span>
                                </a>  --}}
                                <x-utilities.link-create href="{{ route('admin.categories.index') }}" btnType="success pull-right" text="Category List" icon="list"/>

                            </h2><br>
                            {{--  @if(request()->session()->has('message'))
                                <div class="alert alert-success m-5" role="alert">
                                    {{ session('message') }}
                                </div>
                            @endif  --}}
                            <x-alerts.message id="cateroryId" class="text-white" type="success" :message="session('message')"/>
                        </div>
                        <div class="body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                    <thead>
                                        <tr>
                                            <th>Sl</th>
                                            <th>Title</th>
                                            <th>Slug</th>
                                            <th>Description</th>
                                            <th>Status</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>Sl</th>
                                            <th>Title</th>
                                            <th>Slug</th>
                                            <th>Description</th>
                                            <th>Status</th>
                                            <th>Action</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        @foreach ($categories as $category)
                                        <tr>
                                            <td>{{ $loop->iteration }}</td>
                                            <td>{{ $category->title }}</td>
                                            <td>{{ $category->slug }}</td>
                                            <td>{{ $category->description }}</td>
                                            <td><span class="badge {{ $category->is_active ? 'bg-green' : 'bg-pink' }}">{{ $category->is_active ? 'Active' : 'Inactive' }}</span></td>
                                            <td class="text-center" style="white-space:nowrap;">   
                                                <form action="{{ route('admin.categories.restore', $category->id) }}" method="POST" style="display:inline">
                                                    @csrf
                                                    @method('PATCH')
                                                    <x-forms.button onclick="return confirm('Are you sure want to restore ?')" 
                                                        data-toggle="tooltip" data-placement="top" title="RESTORE" icon="restore_from_trash" color="warning" />
                                                </form>     
                                                <form action="{{ route('admin.categories.delete', $category->id) }}" method="POST" style="display:inline">
                                                    @csrf
                                                    @method('DELETE')
                                                    <x-forms.button onclick="return confirm('Are you sure want to delete permanently ?')" 
                                                        data-toggle="tooltip" data-placement="top" title="DELETE" icon="delete_forever" color="danger" />
                                                </form>                                                
                                            </td>
                                        </tr>
                                        @endforeach

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            @push('css')
            {{-- JQuery DataTable Css --}}
            <link href="{{ asset('ui/backend/assets/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css') }}" rel="stylesheet">
            @endpush

            @push('js')
            {{-- Jquery DataTable Plugin Js --}}
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/jquery.dataTables.js') }}"></script>
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js') }}"></script>
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js') }}"></script>
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/extensions/export/buttons.flash.min.js') }}"></script>
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/extensions/export/jszip.min.js') }}"></script>
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/extensions/export/pdfmake.min.js') }}"></script>
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/extensions/export/vfs_fonts.js') }}"></script>
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/extensions/export/buttons.html5.min.js') }}"></script>
            <script src="{{ asset('ui/backend/assets/plugins/jquery-datatable/extensions/export/buttons.print.min.js') }}"></script>
            {{-- Jquery DataTable --}}
            <script src="{{ asset('ui/backend/assets/js/pages/tables/jquery-datatable.js') }}"></script>

            {{-- Bootstrap Latest compiled and minified JavaScript --}}



            {{-- Show Tooltop on Buttons --}}
            <script>
                $(function() {
                    $('[data-toggle="tooltip"]').tooltip()
                })
            </script>

            @endpush

</x-backend.layout.master>